### ISSUE TITLE
Rename `.wavefront_token` to `.wavefront.properties`

### ISSUE THREAD

**Issue by snicoll** [snicoll/wavefront-spring-boot#7]
Considering one can connect to many clusters, it is a bit odd that the local store only supports one token. We should be able to auto-negotiate and restore accounts from more than one URI.

**Comment by howardyoo** [comment]
But there would be a problem of selecting which token user would want to use - as our SDK and calling mechanism doesn't define it explicitly, other than the URL and the token combo. We might want to keep the history of which tokens the user used, and leave the latest URL and token to be the active, so that user can later modify it in the token file.

**Comment by snicoll** [comment]
> But there would be a problem of selecting which token user would want to use 

Why is that? The original starter had a `wavefront.uri` that is now taken care of by the standard Spring Boot property `management.metrics.export.wavefront.uri`. And it allows to specify on which cluster you want the auto-negotiation to happen. 

Here is the use case I had in mind:

* User starts an app with this feature, we auto-negotiate an account for them and all is well
* User has to switch to a different cluster (whatever the reason is) and would like to continue to benefit from this feature. Later on, they would like to return potentially to the original app they had on the first cluster.

Right now this scenario doesn't work very well. When a user has any app with `management.metrics.export.wavefront.uri` set (and no api token) the only thing we can do is try to get a user account with the token on disk without knowing if that's a token for the matching server. That will fail and the only thing the user can really is to remove the token file to start over again. In that case, the original token is lost.

Given that the file is located in the user's home directory, isn't that a valid use case that a user may auto-negotiate accounts to more than one cluster at some point? 

The idea, of course, is to save the token _And_ the Wavefront cluster url from which it was auto-negoatiated.

**Comment by howardyoo** [comment]
So if I remember correctly, the auto-negotiated account would only last for five days and it would expire afterwards, and user has to get a new account after that. Not sure whether this has changed or not...

**Comment by snicoll** [comment]
> So if I remember correctly, the auto-negotiated account would only last for five days and it would expire afterwards, and user has to get a new account after that.

Well that's worth, isn't it? And that doesn't prevent someone to negotiate another account (or simply configure the URI) in that 5 days timeframe.

**Comment by howardyoo** [comment]
No, it does not. So user can re-negotiate new accounts and tokens how many
times that they want (by simply removing the existing token file, I guess).
I think there could be a way to make multiple token configurations existing
and usable by the user - which is okay, but I'm not the one to decide. It
will be a decision of the creator and innovator which may be Clement (and
other contributors, I guess).

**Comment by snicoll** [comment]
That makes sense, thanks. In the meantime we've confirmed that account auto-negotiation is specific to the default cluster and this issue isn't relevant anymore.
